### ISSUE TITLE
Huez resets color to the default color everytime I try to change it

### ISSUE THREAD

**Issue by simonlearnscoding** [vague2k/huez.nvim#13]
Huez worked the first time I set up a colorscheme with it but since then whenever I try to change a colorscheme with it it will resort to using the same color that ive first set up immediately after trying to change that color.

Steps to reproduce: this is my current config
```-- Lazy

return {
  event = 'BufWinEnter',
  'vague2k/huez.nvim',
  dependencies = {
    -- You probably already have this installed, highly reccomended you do.
    'nvim-telescope/telescope.nvim',
    -- If using vim.ui, this plugin will give you a better experience
    'stevearc/dressing.nvim',
  },
  config = function()
    require('huez').setup()
    local colorscheme = require('huez.api').get_colorscheme()
    vim.cmd('colorscheme ' .. colorscheme)
    vim.keymap.set('n', '<leader>co', '<cmd>Huez<CR>', {})
  end,
}
```

**Comment by vague2k** [comment]
What version of neovim are you on? Have you checked that you're on the latest version? I'd start there.

I copy pasted your config and it stills works as intended for me
