### ISSUE TITLE
Theme Manager

### ISSUE THREAD

**Issue by tris203** [vague2k/huez.nvim#14]
If we maintained a list of themes in a MD/Yaml file

Then the plugin could fit clone the themes down and implement new themes 

Questions:

Updates to themes. Maybe a striped version of the way Mason or Lazy works

Do many themes require complicated set up functions. Thinking like cappuccinn flavours etc

If huez handles the download does it handle the loading and configuration too. Perhaps the config file we have also holds info on how to config the colour scheme

**Comment by vague2k** [comment]
Previewing themes in a mason like manner would be cool.

As far as downloading theme n configuration goes, i think insteading of installing it and making huez just a small theme manager, if a user wants to install a theme they can select the theme they want to install and a window will pop up with instructions on how to install with their preferred package manager of choice. Obviously this would require parsing the md or yml file.

**Comment by tris203** [comment]
I see what you are saying. However to preview the theme it would have to be installed/configured. 

So I think if this was to be implemented then the 'theme manager' side is actually almost there?

**Comment by vague2k** [comment]
I'm not saying it shouldnt be attempted, but me personally (and i'm assuming this would be the general consensus) no wants a seperate manager other than their plugin manager.
