### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by eleloi** [vague2k/huez.nvim#32]
Hey, I'm trying this plugin because I love the idea of change colorschemes from time to time.

I saw it can add a theme to a favourite list, but... how? I'm not able to find the key...

And the Live mode, what is it for? Like to install colorshemes via the UI? It don't work for me.

Thank you for this plugin!!

**Comment by vague2k** [comment]
I am literally updating the README for this as we speak haha, I'm already on it

> And the Live mode, what is it for? Like to install colorshemes via the UI? It don't work for me.

This also will be talked about in detail in the docs, but as of right now, multiple people have told me that previewing from this picker is not working, so I'm also in the proccess of debugging this issue (even though it works for me)

**Comment by eleloi** [comment]
Oh, wow, I'm looking forward then!

Trying things I saw the preview mode works if I'm in normal mode, in insert mode don't. Saying just in case.

**Comment by vague2k** [comment]
> Oh, wow, I'm looking forward then!
> 
> Trying things I saw the preview mode works if I'm in normal mode, in insert mode don't. Saying just in case.

Yes this was an oversight on my part, i forgot to include insert mode mappings, will be fixing this after I push the doc changes.
