### ISSUE TITLE
Bug: Cannot use HuezLive, but can preview Huez defaults

### ISSUE THREAD

**Issue by dantearaujo1** [vague2k/huez.nvim#34]
Installed your plugin like the docs, and when trying to use HuezLive and change some colorscheme, it doesnt show the preview and gives back this error:

E5108: Error executing lua: ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:215: attempt to index field '_' (a nil value)
stack traceback:
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:215: in function 'clear'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:39: in function 'run'
        ...local/share/nvim/lazy/lazy.nvim/lua/lazy/manage/init.lua:81: in function 'install'
        ...re/nvim/lazy/huez.nvim/lua/huez-manager/api/selected.lua:43: in function 'lazy_flush'
        ...hare/nvim/lazy/huez.nvim/lua/huez/pickers/live/utils.lua:14: in function 'load_currently_installed'
        ...re/nvim/lazy/huez.nvim/lua/huez/pickers/live/actions.lua:31: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:290: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:289>

If u use :Huez it works, i can preview the default ones and select them, but it seems i cant install any, im using Arch and 
NVIM v0.10.0-dev-2930+g47ba96a6b3
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

i have telescope installed and using lazy package manager.

**Comment by vague2k** [comment]
How are you setting it up?

**Comment by mehalter** [comment]
I also ran into this and realized what the comment in the docs meant. You need to add the `import = "huez-manager.import"` part to your lazy spec.

@vague2k it might be a good idea to explain this better in the README because it's not clear

**Comment by vague2k** [comment]
> @vague2k it might be a good idea to explain this better in the README because it's not clear

You're right, thanks for the feedback!

**Comment by vague2k** [comment]
Just updated the readme to include  `import = "huez-manager.import"`

 @dantearaujo1 let us know if you're still having issues, if you're not i'll consider the issue solved :)

**Comment by dantearaujo1** [comment]
It worked after the import. Thx
