### ISSUE TITLE
Bug: Pressing Esc while in Insert mode closes Huez instead of switching to Normal mode

### ISSUE THREAD

**Issue by amenrio** [vague2k/huez.nvim#35]
Reading the new documentation, I noticed that there are some commands listed for normal mode, but I'm always in insert and any command to  enter normal mode just closes Huez

**Comment by vague2k** [comment]
have you checked that you don't have a key map re-binded somewhere?

**Comment by amenrio** [comment]
I can look into it but I don't know if I'm missing something...

What is the expected use?

I have set up the keybinds in the README, all those commands open Huez in INSERT mode, pressing <C-c>, <Esc> and so just closes Huez.

What key(s) is supposed to put me back into normal mode?

**Comment by amenrio** [comment]
Yes telescope works fine, that's why I was confused thinking that I must have missed something (Wouldn't be the first nor the last time).

Huez is behaving differently. Pressing \<Esc\> just closes any Huez window.

**Comment by vague2k** [comment]
I'll look into this then, maybe there was an error on my part with the implementation of the mapping's actions. I'll ping you if that ok

**Comment by amenrio** [comment]
Sorry if I'm completely mistaken. I dont know lua that much nor telescope or your plugin, but based just on function names, I found this:

https://github.com/vague2k/huez.nvim/blob/c336dbc939253a9fca0af5259f2cbceaf0bba21d/lua/huez/pickers/live/actions.lua#L42

Maybe I'm completely wrong tho. but maybe it was helpful

**Comment by vague2k** [comment]
@amenrio I Tested the changes on my end and escaping from insert mode now goes into normal mode, letting you close the picker from normal mode. 

Let me know if this was the behavior you were expecting.

**Comment by amenrio** [comment]
Yes! That's it! Thank you for fixing it that quickly and good luck going forward!
