### ISSUE TITLE
module huez.api not found

### ISSUE THREAD

**Issue by simonlearnscoding** [vague2k/huez.nvim#41]
After I just updated my plugin it stopped working saiying that huez.
This is my setup on nvim 0.9.5 on arch:

```lua

return {
  event = 'BufWinEnter',
  'vague2k/huez.nvim',
  dependencies = {
    -- You probably already have this installed, highly reccomended you do.
    'nvim-telescope/telescope.nvim',
    -- If using vim.ui, this plugin will give you a better experience
    'stevearc/dressing.nvim',
  },
  config = function()
    require('huez').setup()
    local colorscheme = require('huez.api').get_colorscheme()
    vim.cmd('colorscheme ' .. colorscheme)
    vim.keymap.set('n', '<leader>co', '<cmd>Huez<CR>', {})
  end,
}

```

**Comment by vague2k** [comment]
refer to the readme. Huez has gone through a major ver update. it's now in 1.0.0

**Comment by simonlearnscoding** [comment]
thats my bad. I just updated the setup. I love the updates!

**Comment by vague2k** [comment]
> thats my bad. I just updated the setup. I love the updates!

no problem, let me know if you have anymore issues, thanks for using the plugin! I'll close this issue for now
