### ISSUE TITLE
bug: error in `:Huez` after adding preselection index in the picker 

### ISSUE THREAD

**Issue by vague2k** [vague2k/huez.nvim#49]
@axzilla reference #45 and #15

**Comment by axzilla** [comment]
FYI, this works fine:

```
vim.keymap.set("n", "<leader>tt", ":Huez<CR>", { desc = "Color Themes" })
```

But this not:
```
local pickers = require("huez.pickers")
vim.keymap.set("n", "<leader>tt", pickers.themes, { desc = "Color Themes" })
```

**Comment by vague2k** [comment]
> FYI, this works fine:
> 
> ```
> vim.keymap.set("n", "<leader>tt", ":Huez<CR>", { desc = "Color Themes" })
> ```
> 
> But this not:
> 
> ```
> local pickers = require("huez.pickers")
> vim.keymap.set("n", "<leader>tt", pickers.themes, { desc = "Color Themes" })
> ```

@axzilla let me know if it works now, the function should set opts to nil as of #51 if no arg was passed, also feel free to try out the other pickers by calling the function instead of the command and let me know if you get the behavior?

**Comment by axzilla** [comment]
> @axzilla let me know if it works now, the function should set opts to nil as of https://github.com/vague2k/huez.nvim/pull/51 > if no arg was passed, also feel free to try out the other pickers by calling the function instead of the command and let me > know if you get the behavior?

Works great now, as do the other pickers. Thanks for that!
