### ISSUE TITLE
Dark Theme Displays as Light Theme After Switching from Light Theme

### ISSUE THREAD

**Issue by axzilla** [vague2k/huez.nvim#50]
There is an issue where switching from a light theme to a dark theme causes the dark theme to appear like a light theme.

https://github.com/vague2k/huez.nvim/assets/26936893/08b9c1af-51df-42a2-b2e8-b879fb4babd5

**Comment by vague2k** [comment]
this has been a bit of an issue that i've known for a while now, 

i just can't tell if it's something to do with Huez or a seperate issue with neovim entirely, i'd have to check
