### ISSUE TITLE
Support for custom themes/theme overrides?

### ISSUE THREAD

**Issue by zeitchef** [vague2k/huez.nvim#7]
I tinker with themes a LOT and didn't immediately see a way to add custom themes or theme overrides within the plugin - can you confirm if this is supported?

**Comment by vague2k** [comment]
right now "tinkering" isn't something you can do with this plugin. But i'm curious as to what you mean by "tinkering". If something worth implementing, I'll see if it makes sense

**Comment by zeitchef** [comment]
By "tinkering" I just mean overriding highlights - I just can't seem to roll with a stock theme ;) I'd love that when selecting a certain theme, these per-theme overrides would be applied.

**Comment by vague2k** [comment]
Why do you prefer editing color schemes overrides through the plugin rather than going into your config and declaring overrides there?

**Comment by zeitchef** [comment]
At the moment this is precisely what I do, but the moment I change my theme that's a lot of configuration that I need to either change manually or delete. Some plugins allow overriding the theme directly, and depending on which theme I load, these overrides are then applied. Just about every modern theme for Neovim allows for some sort of overriding - check out my current theme of choice to see what I mean: https://github.com/catppuccin/nvim

**Comment by zeitchef** [comment]
This could definitely be taken care of at the theme level, but it's not entirely clear to me where the themes for Huez are sourced - do you include them or are they user-supplied?

**Comment by vague2k** [comment]
Huez only lets you preview color schemes **(If you're using it with telescope)** and persists them through sessions without modifying the config. 

Any themes that are in the list available to you and not omitted from being seen by the plugin, you've installed.

**Comment by zeitchef** [comment]
Ah ok, sorry - then I've completely misunderstood the scope of this plugin. Thanks for the clarification!
